CREATE OR REPLACE TRIGGER PROTECT_DELETE
    BEFORE DELETE
    ON TAKES
    FOR EACH ROW
    WHEN ( OLD.YEAR = 2009 AND OLD.SEMESTER = 'Fall' )
DECLARE
    XCEP EXCEPTION ;
    PRAGMA EXCEPTION_INIT ( XCEP,-20001 );
BEGIN
    DBMS_OUTPUT.PUT_LINE('YEAR 2009 SEMESTER FALL CANT BE DELETED');
    RAISE XCEP;
END;



